server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
  cache:
    type: redis
    redis:
      enable-statistics: true
      key-prefix: url-
      use-key-prefix: true
      cache-null-values: false
      time-to-live: 1H
    cache-names:
      - document
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    # Mongo service
    mongodb:
      host: localhost
      port: 27017
      database: url-shortener
      auto-index-creation: true

github:
  aaivan28:
    url-shortener:
      redirect-base-url: https://www.google.com

management:
  endpoints:
    web:
      exposure:
        include: "*"